apiVersion: apps/v1
kind: Deployment
metadata:
  name: letsplay
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: letsplay
  template:
    metadata:
      labels:
        deployment: letsplay
    spec:
      containers:
        - name: letsplay
<<<<<<< HEAD
          image: harbor-staging.aptan.cloud/letsplay/letsplay:8
=======
          image: harbor-staging.aptan.cloud/letsplay/letsplay:7
>>>>>>> master
          ports:
            - containerPort: 8080
