apiVersion: apps/v1
kind: Deployment
metadata:
  name: letsplay
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: letsplay
  template:
    metadata:
      labels:
        deployment: letsplay
    spec:
      containers:
        - name: letsplay
          image: harbor-staging.aptan.cloud/letsplay/letsplay:6
          ports:
            - containerPort: 8080
