apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: letsplay-vs
  namespace: letsplay
spec:
  hosts:
    - letsplay.aptan.cloud
    - letsplay2018.com
  gateways:
    - istio-system/gateway
  http:
    - route:
        - destination:
            host: letsplay.letsplay.svc.cluster.local
            port:
              number: 8080
